---
title: "Meat Trial results"
author: "Andrew Mertens"
date: "Sept 28, 2020"
output:
  word_document:
    reference_docx: plant_trial_report_format.docx
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
op = function(x, d=2) sprintf(paste0("%1.",d,"f"), x) 
 library(pander)
panderOptions('digits', 2)
panderOptions('round', 2)
panderOptions('keep.trailing.zeros', TRUE)
panderOptions('graph.fontsize', 8)

```


```{r include=F}



print_fun <- function(res, binomial=F, Y=F){
  Z<-qnorm(.025/5,lower.tail=FALSE)

  if(binomial){

    res$ci_lb = exp(res$est - 1.96*res$se)
    res$ci_ub = exp(res$est + 1.96*res$se)
    res$adjCI1 <- exp(res$est - Z*res$se)
    res$adjCI2 <- exp(res$est + Z*res$se)
    #res$reference=res$reflevel
    
    res <- res %>% subset(., select = c(intervention, reference, RR, ci_lb, ci_ub,  p, adjCI1, adjCI2, corrected.p))
    res[,3:9] <- round(res[,3:9], 3)
  }else{
    
    res$ci_lb = (res$est - 1.96*res$se)
    res$ci_ub = (res$est + 1.96*res$se)
    
    #calculate corrected CI's
    res$adjCI1 <- res$est - Z*res$se
    res$adjCI2 <- res$est + Z*res$se



    
    #res$reference=res$reflevel
    res$coef=res$est
    if(Y==T){
    res <- res %>% subset(., select = c(Y, intervention, reference, coef, ci_lb, ci_ub,  p, adjCI1, adjCI2, corrected.p))
        res[,-c(1:3)] <- round(res[,-c(1:3)], 3)

    }else{
    res <- res %>% subset(., select = c(intervention, reference, coef, ci_lb, ci_ub,  p, adjCI1, adjCI2, corrected.p))
    res[,3:9] <- round(res[,3:9], 3)
    }
  }
  return(res)
}



print_fun_polr <- function(res){
  res <- res %>% rename(se=Std..Error, est=Value, tr=coef ) %>%
    mutate(
          ci_lb = exp(est - 1.96*se),
          ci_ub = exp(est + 1.96*se),
          RR = exp(est),
          corrected.p = ifelse(corrected.p>1, 1, corrected.p)
    ) %>%
    subset(., select=c(tr, RR, se, ci_lb, ci_ub, p, corrected.p))


    res[,3:7] <- round(res[,3:7], 3)
 
  return(res[1:3,])
}

```

## Unadjusted regressions results


```{r, echo=F}
  load(here("results/unadjusted_regression_results.rdata"))
cat("Outcome variable: ",Yvars[1],":\n")
print_fun(res_Y1_unadj, binomial=F)
cat("Outcome variable: ",Yvars[2],":\n")
print_fun(res_Y2_unadj, binomial=F)
cat("Outcome variable: ",Yvars[3],":\n")
print_fun(res_Y3_unadj, binomial=F)

```

## Adjusted regressions results


```{r, echo=F}
  load(here("results/adjusted_regression_results.rdata"))
cat("Outcome variable: ",Yvars[1],":\n")
print_fun(res_Y1, binomial=F)
cat("Outcome variable: ",Yvars[2],":\n")
print_fun(res_Y2, binomial=F)
cat("Outcome variable: ",Yvars[3],":\n")
print_fun(res_Y3, binomial=F)

```


## Unadjusted secondary regressions results


```{r, echo=F}
  load(here("results/unadjusted_secondary_results.rdata"))

print_fun(res_sec, binomial=F, Y=T)

```

## Adjusted secondary regressions results


```{r, echo=F}
  load(here("results/adjusted_secondary_results.rdata"))

print_fun(res_sec_adj, binomial=F, Y=T)

```


## sensitivity ordered logistic regressions results


```{r, echo=F}
  load(here("results/unadjusted_ordered_logistic_results.rdata"))


cat("Outcome variable: ",Yvars[1],":\n")
print_fun_polr(ord_Y1$res)
cat("Outcome variable: ",Yvars[2],":\n")
print_fun_polr(ord_Y2$res)
cat("Outcome variable: ",Yvars[3],":\n")
print_fun_polr(ord_Y3$res)
```

## Unadjusted moderation results - interaction P-values

```{r, echo=F}
  load(here("results/unadjusted_moderation_analysis_results.rdata"))

pander(res_unadj, split.table = Inf)

```

## Unadjusted moderation results - full results

```{r, echo=F}


# resfull_unadj <- resfull_unadj %>% select(subgroup,RR,RR.lb,RR.ub,P, int.p,  control, treatment,outcome,V)
pander(resfull_unadj, split.table = Inf)

```