---
title: "table1"
author: "Andrew Mertens"
date: "10/24/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=F, warning=F}
library(here)
library(tidyverse)
library(table1)

load(here("data/analysis_dataset.Rdata"))

Wvars <- c("tr","ave_cov_att","pre.plant.attitudes","Pre.behavioral.int","Age","Gender",
           "Race","Education","income","urbanrural","political.affiliatio","pets")


d <- d %>% subset(., select = Wvars) %>%
  rename(
  `Attitudes towards Plant-Based Alternatives (pre message)` = pre.plant.attitudes,
  `Intentions to Reduce Meat Consumption (pre message)` = Pre.behavioral.int,
  `Average Attitudes towards COVID-19` = ave_cov_att,
  Income=income,
  `Area of Residence (urban to rural)` = urbanrural,
  `Political Affiliation` = political.affiliatio,
  `Pet Ownership` = pets
) %>%
  mutate(Race=factor(Race, labels=c("Black","White","Other")))








# table1(~ ave_cov_att+pre.plant.attitudes+Pre.behavioral.int+Age+Gender+Race+Education+income+urbanrural+political.affiliatio+pets |tr, data=d)

table1(~. |tr, data=d)

```
